### ISSUE TITLE
use \Yurun\Util\HttpRequest;  这个公用请求SDK类怎么找不到文件？

### ISSUE THREAD

**Issue by xiao-cjiu** [iicc/pay-sdk#1]
你在 src/Base.php  中使用的  $this->http = new HttpRequest;   这个HttpRequest 类为哪里啊，找遍了也找不到，是不是没有打包进来？

**Comment by xiao-cjiu** [comment]
在 Base.php 基类里面用到的 \Yurun\Util\   下的类都没有啊，封装的工具类去哪里了？？？

**Comment by iicc** [comment]
使用下面的命令安装
composer require iicc/pay-sdk
会自动安装依赖关系的.
